package com.SdataG.sunwell.client;

/** Generated by tools/patch_lantern_assets.py — do not edit by hand. */
public final class LanternModelBounds {

    public record FlameBox(float minX, float minY, float minZ, float maxX, float maxY, float maxZ) {}

    public static final FlameBox ORB_HANGING = new FlameBox(6F, 6.15F, 6F, 10F, 10.65F, 10F);
    public static final FlameBox ORB_FLOOR = new FlameBox(6F, 2.4499999999999993F, 6F, 10F, 6.949999999999999F, 10F);
    public static final FlameBox CAGE_HANGING = new FlameBox(5.05F, 4.45F, 5.05F, 10.95F, 12.35F, 10.95F);
    public static final FlameBox CAGE_FLOOR = new FlameBox(5.05F, 0.7500000000000002F, 5.05F, 10.95F, 8.649999999999999F, 10.95F);

    private LanternModelBounds() {
    }

    public static FlameBox orbBox(boolean hanging) {
        return hanging ? ORB_HANGING : ORB_FLOOR;
    }

    public static FlameBox cageBox(boolean hanging) {
        return hanging ? CAGE_HANGING : CAGE_FLOOR;
    }

    public static FlameBox glowBox(boolean soul, boolean hanging) {
        FlameBox orb = orbBox(hanging);
        float pad = 0.35f;
        return new FlameBox(
                orb.minX() - pad,
                orb.minY() - pad,
                orb.minZ() - pad,
                orb.maxX() + pad,
                orb.maxY() + pad,
                orb.maxZ() + pad
        );
    }

    public static FlameBox[] orbSegments(boolean hanging) {
        if (hanging) {
            return new FlameBox[] {
                    new FlameBox(6F, 6.65F, 6F, 10F, 9.65F, 10F),
                    new FlameBox(6.3F, 6.15F, 6.3F, 9.7F, 6.65F, 9.7F),
                    new FlameBox(6.6F, 9.35F, 6.6F, 9.4F, 10.65F, 9.4F),
            };
        }
        return new FlameBox[] {
                    new FlameBox(6F, 2.9499999999999993F, 6F, 10F, 5.949999999999999F, 10F),
                    new FlameBox(6.3F, 2.4499999999999993F, 6.3F, 9.7F, 2.9499999999999993F, 9.7F),
                    new FlameBox(6.6F, 5.649999999999999F, 6.6F, 9.4F, 6.949999999999999F, 9.4F),
        };
    }
}
